### ISSUE TITLE
How to make a 7200 min continuously oscillating sinewave?

### ISSUE THREAD

**Issue by cuong450** [taborlab/Iris#305]
It seems not possible to do this programmaticly?  For the existing interface, you can only choose 1 sine wave period over a set time duration, but not combine many of these sine wave periods? If I am wrong, please direct me to manual. Thank you

**Comment by SynbioLucas** [comment]
Sorry, but I'm not clear on exactly what program you're trying to make. The attached LPF (just remove the .txt from the end of the filename) has a sine wave with 7200min period on the top LED. Presumably this isn't what you wanted?

[program.lpf.txt](https://github.com/taborlab/Iris/files/1202571/program.lpf.txt)

If you're trying to program multiple waveforms (including multiple sine waveforms) onto the same LED in the same well, this is unfortunately [not supported by Iris](http://taborlab.github.io/Iris/documentation/documentation.html#add-waveforms-to-the-experiment). The best way to do this is to write a simple script using the [Iris Python API](http://taborlab.github.io/Iris/documentation/documentation.html#writing-an-lpf-using-python). You can find an [example script here](https://github.com/taborlab/Iris/blob/master/Python/ProduceLPFDemo.ipynb).
